name = "agyani-landing"
compatibility_date = "2025-06-09"
main = "workers-site/index.js"

[site]
bucket = "dist"

[build]
command = "npm run build"
cwd = "."

[env.production]
name = "agyani-landing"
route = "www.agyani.me/*"
zone_id = "a69c900793510c8182a593ce5b8208b4"

[env.production.vars]
ENVIRONMENT = "production"

# Add static asset handling
[build.upload]
format = "service-worker" 