name = "agyani-landing"
compatibility_date = "2025-06-09"
main = "workers-site/index.js"

[site]
bucket = "dist"

[build]
command = "npm run build"
cwd = "."

[env.production]
name = "agyani-landing"
routes = [
  "agyani.me/*",
  "www.agyani.me/*"
]
zone_id = "a69c900793510c8182a593ce5b8208b4"

[env.production.vars]
ENVIRONMENT = "production"

# Add static asset handling
[build.upload]
format = "service-worker"

# Add KV namespace for assets
kv_namespaces = [
  { binding = "ASSETS", id = "__agyani-workers_sites_assets", preview_id = "__agyani-workers_sites_assets" }
] 